#!/usr/bin/env bash
# shellcheck disable=SC2034

iso_name="EnigmaOS"
iso_label="EnigmaOS_$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y%m)"
iso_publisher="Sanchit Sahni https://github.com/sanchitsahni07/"
iso_application="EnigmaOS Live/Installation/Rescue CD"
iso_version="$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m.%d)"
install_dir="arch"
buildmodes=('iso')
bootmodes=('bios.syslinux.mbr' 'bios.syslinux.eltorito'
           'uefi-ia32.grub.esp' 'uefi-x64.grub.esp'
           'uefi-ia32.grub.eltorito' 'uefi-x64.grub.eltorito')
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
airootfs_image_tool_options=('-comp' 'xz' '-Xbcj' 'x86' '-b' '1M' '-Xdict-size' '1M')
bootstrap_tarball_compression=('zstd' '-c' '-T0' '--auto-threads=logical' '--long' '-19')
file_permissions=(
  ["/etc/shadow"]="0:0:400"
  ["/etc/gshadow"]="0:0:0400"
  ["/etc/sudoers.d"]="0:0:750"
  ["/root"]="0:0:750"
  ["/root/.automated_script.sh"]="0:0:755"
  ["/root/.gnupg"]="0:0:700"
  ["/root/customize_airootfs.sh"]="0:0:755"
  ["/usr/local/bin/choose-mirror"]="0:0:755"
  ["/usr/local/bin/xflock4"]="0:0:755"
  ["/etc/skel/.local/share/bin/amdgpu.py"]="0:0:777"
  ["/etc/skel/.local/share/bin/batterynotify.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/brightnesscontrol.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/cliphist.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/cpuinfo.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/dontkillsteam.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/gamelauncher.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/gamemode.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/globalcontrol.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/gpuinfo.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/keybinds_hint.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/keyboardswitch.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/logoutlaunch.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/mediaplayer.py"]="0:0:777"
  ["/etc/skel/.local/share/bin/notifications.py"]="0:0:777"
  ["/etc/skel/.local/share/bin/polkitkdeauth.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/quickapps.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/resetxdgportal.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/rofilaunch.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/rofiselect.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/screenshot.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/swwwallbash.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/swwwallcache.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/swwwallkon.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/swwwallpaper.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/swwwallselect.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/sysmonlaunch.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/systemupdate.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/testrunner.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/themeselect.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/themeswitch.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/volumecontrol.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wallbash.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wallbashcava.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wallbashcode.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wallbashdiscord.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wallbashdunst.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wallbashqt.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wallbashspotify.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wallbashtoggle.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wbarconfgen.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/wbarstylegen.sh"]="0:0:777"
  ["/etc/skel/.local/share/bin/windowpin.sh"]="0:0:777"
)
